name: Greet Everybody
# This workflow is triggered on pushes to the repository.
on: [push]

jobs:
  my_first_job:
    # Job name is Greeting
    name: Greeting
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # This step uses the hello-world-action stored in this workflow's repository.
    - uses: ./.github/actions/my-first-action
      with:
        myInput: 'Octocat'
      id: hello
    # This step prints the time.
    - run: echo "The time was ${{ steps.hello.outputs.time }}"
    # See what's in the dir
    - run: ls -l
  make_release:
    # Job name is Greeting
    name: Create Release
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # This step uses the hello-world-action stored in this workflow's repository.
    - uses: ./.github/actions/make_release
      id: make_release
  build:
    name: Build
    runs-on: ubuntu-latest
    strategy:
      matrix:
        #Dockerfile.centos.7
        #Dockerfile.leap.15
        #Dockerfile.leap.42.3
        #Dockerfile-mockbuild.centos.7
        #Dockerfile-rpmbuild.sles.12.3
        #Dockerfile.sles.12.3
        #Dockerfile.ubuntu.18.04
        distro: [centos.7, ubuntu.18.04]
    steps:
    - uses: actions/checkout@v1
    - name: Build in Docker Image
      env:
        DOCKER_IMAGE: ${{ github.repository }}:${{ github.sha }}
      run: |
        docker build . --file utils/docker/Dockerfile.centos.7 --tag ${DOCKER_IMAGE} &&
        docker run ${DOCKER_IMAGE}
