name: Workflow
# This workflow is triggered on pushes to the master branch of the repository.
on:
  push:
    branches:
    - master

jobs:
  make_release:
    # Job name is Greeting
    name: Create Release
    # This job runs on Linux
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    # This step uses the hello-world-action stored in this workflow's repository.
    - uses: ./.github/actions/make_release
      id: make_release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
